# Generated by Django 4.2.3 on 2023-07-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photogdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('PMOB', models.IntegerField(blank=True, null=True)),
                ('PEM', models.EmailField(blank=True, max_length=254, null=True)),
                ('PIM', models.ImageField(blank=True, null=True, upload_to='pic')),
            ],
        ),
    ]
