# Generated by Django 4.2.3 on 2023-07-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickapp', '0002_remove_photogdb_pem_remove_photogdb_pmob'),
    ]

    operations = [
        migrations.CreateModel(
            name='savecatdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcat', models.CharField(blank=True, max_length=100, null=True)),
                ('pimg', models.ImageField(blank=True, null=True, upload_to='pic')),
                ('pdes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
