# Generated by Django 4.2.3 on 2023-07-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickapp', '0003_savecatdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='saveitemdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp', models.CharField(blank=True, max_length=100, null=True)),
                ('pn', models.CharField(blank=True, max_length=100, null=True)),
                ('ph', models.ImageField(blank=True, null=True, upload_to='')),
                ('pd', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
