# Generated by Django 4.2.3 on 2023-07-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickapp', '0004_saveitemdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveitemdb',
            old_name='cp',
            new_name='category_photo',
        ),
        migrations.RenameField(
            model_name='saveitemdb',
            old_name='pd',
            new_name='p_description',
        ),
        migrations.RenameField(
            model_name='saveitemdb',
            old_name='ph',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='saveitemdb',
            old_name='pn',
            new_name='photo_name',
        ),
    ]
