# Generated by Django 4.2.3 on 2023-08-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickapp', '0005_rename_cp_saveitemdb_category_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('SIM', models.ImageField(blank=True, null=True, upload_to='pic')),
                ('S_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='saveitemdb',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
