# Generated by Django 4.2.3 on 2023-08-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickapp', '0007_rename_s_description_servicedb_s_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogdb',
            name='desig',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
