# Generated by Django 4.2.3 on 2023-08-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickapp', '0008_photogdb_desig'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicedb',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicedb',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
