# Generated by Django 4.2.3 on 2023-08-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickapp', '0009_servicedb_price_servicedb_time_servicedb_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedb',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
